Bugfix/fix for messageplaybook feature variant 1 (separate class)
russe-g/KafkaEsque pull request #1
Opened 2024-07-18 11:52 UTC by russe-g

2024-07-19 08:04 UTC, enji7 requested changes

2024-07-19 08:04 UTC, enji7 commented on src/main/java/at/esque/kafka/topics/KafkaMessageForMessageBook.java
> +    public void setKeyType(String keyType) {
Dieser Setter sollte unmittelbar unter dem entsprechenden Getter stehen (also immer paarweise).

2024-07-19 08:04 UTC, enji7 commented on src/test/java/at/esque/kafka/ControllerTest.java
> +        assertEquals(2, messagesToSend.size());
Hier könntest du auch den Inhalt der Messages verifizieren.

2024-07-19 08:04 UTC, enji7 commented on build.gradle
> +    testImplementation 'de.saxsys:jfx-testrunner:1.2'
Hierbei dürfte es sich um folgendes Projekt handeln:

https://github.com/sialcasa/jfx-testrunner

Dieses Projekt scheint aber seit 9 Jahren nicht mehr angefasst worden zu sein. Evtl. stattdessen TestFX verwenden?

https://github.com/TestFX/TestFX

2024-07-19 11:28 UTC, enji7 approved these changes

2024-07-19 11:28 UTC, enji7 commented on src/test/java/at/esque/kafka/ControllerTest.java
> +
Überflüssige Leerzeile.

2024-07-22 08:31 UTC, deimelm commented on src/main/java/at/esque/kafka/topics/KafkaMessageForMessageBook.java
Sind die Files im richtigen Package? Sollten die Models nicht eigentlich im model Ordner liegen?

2024-07-23 08:39 UTC, russe-g commented on src/main/java/at/esque/kafka/topics/KafkaMessageForMessageBook.java
Die 2 von mir angegriffenen Klassen hab ich verschoben.

2024-07-23 09:20 UTC, isabellanake approved these changes

2024-07-25 09:29 UTC, merged